floodlight/loxigen

- java_gen/java_type.py
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchField.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchFields.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFBitMask512.java
> In port 512

- openflow_input/bsn_lua
> openflow_input: add bsn_lua extensions for commands and notifications

- openflow_input/bsn_tlv
> openflow_input: add more TLVs for conntrack

- c_gen/templates/of_object.c
- openflow_input/bsn_tlv
- py_gen/codegen.py
- py_gen/oftype.py
- py_gen/templates/_message_extra.py
- py_gen/templates/module.py
Reviewer: @wilmo119
The of_bsn_tlv_bucket class exposed some issues in the C and Python backends
due to its recursive definition.
> recursive TLV fixes

- openflow_input/bsn_pktin_flag
> openflow_input: add OFP_BSN_PKTIN_FLAG_ARP_CACHE

- wireshark_gen/field_info.py
- wireshark_gen/templates/_oftype_readers.lua
- wireshark_gen/templates/openflow.lua
> Wireshark improvements for OF 1.4

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPv4AddressTest.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPv6AddressTest.java
> Use unsigned long comparison in IPv6Address.compareTo()

- Makefile
openflowj should be rebuilt after change pre-written files.
> Rebuild openflowj when pre-written files' changed

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/annotations/Immutable.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/Match.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/DatapathId.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/HashValue.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4AddressWithMask.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/MacAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFBufferId.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFErrorCauseData.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFGroup.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPort.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPortBitMap.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFVlanVidMatch.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/VlanVid.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/util/PrimitiveSinkUtils.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/OFPortDescTest.java
Fix literal characters, html tags, and malformed usages.
> Fix malformed javadoc

- openflow_input/bsn_pktin_flag
> openflow_input: add OFP_BSN_PKTIN_FLAG_ARP_TARGET

- openflow_input/bsn_tlv
> add vlan_pcp tlv

- openflow_input/bsn_tlv
> Add a few tlvs for tag stripping

- openflow_input/bsn_port_counter
> Add rx port counter bad_vlan.

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFGroup.java
> Fix small bug in pre-written OFGroup.java. Replace MAX with ZERO.

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPAddressTest.java
> add isMulticast() in IPAddress

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPortBitMap512.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/OFPortBitMapTest.java
A dup of original class, changing 128 bit into 512 bit. Add unit tests.
> Add 512-bit variation of OFPortBigMap

- openflow_input/standard-1.3
> Fixed table feature property align to 8 bytes

- openflow_input/bsn_tlv
> openflow_input: add bsn_tlv vlan_vid_mask

- openflow_input/bsn_tlv
> openflow_input: add more BSN TLVs

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchField.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/DatapathId.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/MacAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFBooleanValue.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/DatapathIdTest.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/MacAddressTest.java
> DatapathId and MacAddress factory methods

- java_gen/java_type.py
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchField.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/VxlanNI.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/VxlanNITest.java
Reviewer: @andi-bigswitch @gregor-bsn
> add VxLAN Network Identifier type to the Openflow library

- java_gen/pre-written/pom.xml
- openflow_input/bsn_tlv
> [Java-0.9.x] Cherry-pick  openflow_input: add ipv6 TLV, bump version to 0.9.1

- openflow_input/bsn_tlv
> openflow_input: add decap TLV

- openflow_input/bsn_tlv
> add vxlan tlvs

- openflow_input/bsn_tlv
> openflow_input: add storm control TLVs

- openflow_input/bsn_pktin_flag
> IGMP and PIM packet-in reasons.

- openflow_input/bsn_tlv
> add nexthop_type_vxlan tlv for ecmp gentable

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/MacAddress.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/MacAddressTest.java
> Major oversight in test and typo

- openflow_input/bsn_tlv
> New TLV multicast_interface_id.

- openflow_input/bsn_pktin_flag
> add vxlan src ip lookup failure pktin reason

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPAddressTest.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPv4AddressTest.java
Reviewer: @andi-bigswitch @gregor-bsn
> IPAddress boolean and factory methods

- openflow_input/bsn_tlv
> Status TLV.

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6AddressWithMask.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPv6AddressTest.java
Reviewer: @andi-bigswitch @gregor-bsn
> Modified EUI-64 format interface identifier utilities in IPv6Address LOXI-74

- openflow_input/bsn-1.3
- openflow_input/standard-1.2
- openflow_input/standard-1.3
- openflow_input/standard-1.4
Thanks for helping resolve the problems I was having earlier.
Opening a new pull request that supercedes #438.
> Add of_bsn_base_error and of_bsn_error.

- openflow_input/bsn_tlv
> Add vfi tlv for VXLAN VPN

- openflow_input/bsn_tlv
> Add new tlv's for vxlan and dcbx feature vfp entries

- openflow_input/bsn_tlv
Similar to flow-table priority.
> Add gentable entry-priority tlv

- openflow_input/bsn_tlv
Reviewer: @shudongz @wilmo119 
I also updated the wiki page (https://bigswitch.atlassian.net/wiki/display/BSC/Controller-Switch+Interaction+Enhancements) with some more details.
> Added new TLVs for GRE tunnel gen table

- openflow_input/bsn_tlv
cc @poolakiran @meiyangbigswitch @nsong
> Add new vxlan-egress and cpu lag indicator tlvs

- openflow_input/bsn_tlv
> add of_bsn_tlv_uint64_list and fix of_bsn_tlv_vlan_mac_list

- loxi_front_end/frontend.py
- loxi_front_end/parser.py
- openflow_input/bsn_gentable
- openflow_input/standard-1.0
- openflow_input/standard-1.1
- openflow_input/standard-1.2
- openflow_input/standard-1.3
- openflow_input/standard-1.4
- utest/test_frontend.py
- utest/test_parser.py
> syntax for field length members

- README.md
Reviewer: @rlane  @rizard 
Trivial update for the README...
> Update README.MD for versions 1.4.1 and 1.5.1

- openflow_input/bsn_tlv
> Add disable_src_mac_check tlv

- openflow_input/bsn_tlv
> Add drop tlv

- openflow_input/bsn_tlv
> Add BSN IPV6 Prefix TLV

- openflow_input/bsn_pktin_flag
> ICMPV6 packet-in reason.

- py_gen/templates/connection.py
> pyloxi: support connecting over a unix domain socket

- openflow_input/bsn_tlv
CC: @meiyangbigswitch @premsharma1 
Updated https://bigswitch.atlassian.net/wiki/display/CORP/OpenFlow+Extensions#OpenFlowExtensions-TLVExtensions
> TLV ndp_offload

- openflow_input/bsn_tlv
> ipv6 src/dst tlvs

- openflow_input/bsn_tlv
> Add TLV: push_vlan_on_ingress.

- openflow_input/bsn_tlv
Reviewer: @andi-bigswitch @Sovietaced
> Add apply packets/bytes to use for gentab status replies

- openflow_input/bsn_tlv
> Update description of apply_packets/apply_bytes

- openflow_input/bsn_tlv
Reviewer: @poolakiran @harshsin
> Add eth_type, ecn, tcp_flags, l3 interface class id, l3 src class id, and l3 dst class id TLVs

- openflow_input/bsn_tlv
Reviewer: @kenchiang 
CC: @nsong
> New TLVs ingress_port_group_id, ingress_port_group_id.

- py_gen/templates/_pretty_print.py
- py_gen/templates/util.py
> SWL-3216 IPV6 address pretty_print function.

- java_gen/pre-written/pom.xml
> Update version of slf4j

- openflow_input/bsn_tlv
> Add data_mask tlv.

- openflow_input/bsn_tlv
Reviewer: @nick-bsn @andi-bigswitch 
Add tlv to indicate port usage.
> Add port_usage tlv

- openflow_input/bsn_pktin_flag
> SWLVX-5 Create new pktin flag for INGRESS_ACLs with OFPP_LOCAL in action.

- openflow_input/bsn_tlv
Reviewer: @andi-bigswitch 
CC: @wilmo119
> Add tri-valued tlv for auto negotiation

- openflow_input/bsn_gentable
> Add of_bsn_gentable_error and of_bsn_gentable_full_error.

- java_gen/pre-written/pom.xml
> Update Maven Dependencies

- openflow_input/bsn_tlv
Reviewer: @kenchiang 
CC: @meiyangbigswitch @shudongz 
Controller can tell switch about what hash algorithm to be
used for LAG/ECMP member selection.
> SWL-3343 hash_algorithm TLV.

- openflow_input/bsn_tlv
Reviewer: @kenchiang @skini-bsn
> BVS-7800 use_peer_when_empty TLV.

- openflow_input/bsn_port_desc_properties
- openflow_input/bsn_tlv
Reviewer: @kenchiang @Sovietaced @skini-bsn
> SWL-3735 speed_capabilities bsn port description property, port_speed_gbps TLV.

- openflow_input/bsn_tlv
Reviewer: @shudongz @andi-bigswitch
> Add tlv: push_vlan_on_egress.

- java_gen/pre-written/pom.xml
Reviewer: @andi-bigswitch 
This updates the maven dependencies that we can update (not guava) to the latest stable version.
> Update maven dependencies and bump version

- openflow_input/bsn_forward_error_correction
Reviewer: @kenchiang @wilmo119 
* Add an enum as reviewed for the FEC configuration state
> [SWL-4374] Add an enum for FEC configuration state

- java_gen/java_type.py
- openflow_input/bsn_port_desc_module_eeprom
> BSC-10447 module eeprom info

- openflow_input/bsn_tlv
Reviewer: @kenchiang @poolakiran
> Add bfd variables

- wireshark_gen/templates/openflow.lua
Reviewer: @kenchiang 
Ken, would you take a peek?  Has anyone been using the lua dissector in recent wirewharks?
> Update lua dissector name ("eth" doesn't seem to work in 2.x)

- .build/push-artifacts.sh
Reviewer: @JanStrauss 
Jan this is the equivalent of the appliance-artifacts for loxigen. This was failing earlier when run for a branch for which the destination doesn't have an equivalent branch yet.
The strategy taken here is to 
1. list all the commit hashes of the current branch for the source repository (i.e., loxigen)
2. then step through the commit history of the master branch on the target repo (loxigen-artifact) towards the root, and try to find a commit whose `loxi-revision` is contained in (1)
3. then create a new new branch at that position.
> push-artifacts: support new branches

- openflow_input/bsn_tlv
Reviewer: @poolakiran @kenchiang
> SWL-5205: OFAD - QinQ feature support(loxigen)

- openflow_input/bsn_tlv
Reviewer: @kenchiang @3mp4y5 @shudongz 
Adding an option to denote dropping gtpc packets at the SN
> BT-7871 Adding a loxigen struct to denote dropping of gtpc packets.

- openflow_input/bsn_tlv
Reviewer: @poolakiran @harishraghavendra
> Add dns analytics TLV

- openflow_input/bsn_tlv
Reviewer: @archerhungbsn @kenchiang
> SWL-5261: TLV src_mac_cml.

- openflow_input/bsn_port_desc_properties
Reviewer: @poolakiran @kenchiang 
Implementation of new port features as per below design
https://bigswitch.atlassian.net/wiki/spaces/BSC/pages/889913608/Port+features+enhancement
> SWL-4344: New port features - AN and FEC Configurable & Conflict changes

- Jenkinsfile
- docker/Dockerfile
CC: @andi-bigswitch @Andre-Bigswitch
> try building in bionic

- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/OFMessageTest.java
- java_gen/templates/of_class.java
> LOXI-84: enforce maximum OF message length while writing to buffer

- openflow_input/bsn_tlv
Reviewers: @kenchiang @poolakiran @wilmo119 
Added new TLV - egress sampling rate for Egress Sflow.
> bsn_tlv: added new tlv - egress sampling rate

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/OFMessageReader.java
Reviewer: @weifanfu-bsn @andre-bigswitch @ronaldchl
> LOXI-85: document behavior of OFMessageReader

- openflow_input/bsn_tlv
Add redundant_mgmt_reselect based on the primary_reselect in https://www.kernel.org/doc/Documentation/networking/bonding.txt
> Add redundant_mgmt_reselect

- openflow_input/bsn_tlv
Reviewer: @3mp4y5 
This is what I have in mind for the new TLVs
> Add lcore, thread, mgmt, socket, and load TLVs

- openflow_input/bsn_tlv
> SWL-6104: admin_state TLV

- openflow_input/bsn_tlv
> Added matched_count & lookup_count tlvs

- openflow_input/bsn_tlv
Reviewer: @rizard @poolakiran @junaid-bsn
> Updated TLV - bsn_ip_fragmentation value with enum

- openflow_input/bsn_tlv
Reviewer: @wilmo119 @poolakiran @rizard
> Added new TLV for push_two_tags_capability

- openflow_input/bsn_tlv
Reviewer: @3mp4y5 @rizard @AnuragChowdhary-bsn
> Add metadata and packet_field TLVs

- docker/Dockerfile
- openflow_input/bsn_tlv
> Add no_drop TLV

- openflow_input/bsn_tlv
Reviewer: @harishraghavendra @poolakiran @nick-bsn
> swl-6439 add dhcpv6 option fields

- openflow_input/bsn_tlv
Reviewer: @poolakiran @harishraghavendra
> Use dedicated option tlvs

- openflow_input/bsn_generic_command
> Add of_bsn_generic_command_reply (paired with of_bsn_generic_command)

- openflow_input/bsn_tlv
> Add action_state TLV

- openflow_input/bsn_tlv
Reviewer: @harishraghavendra
CC: @zhaodong-bsn
> [SWL-6518] lag_type TLV, OFP_BSN_LAG_FLAG_ADD_PEER_ON_EMPTY

- openflow_input/bsn_port_desc_properties
> Add additional FEC capabilities for reporting.

- openflow_input/bsn_tlv
Reviewer: @harishraghavendra
CC: @zhaodong-bsn
> [SWL-6518] ccf_feature TLV.

- openflow_input/bsn_tlv
CC: @harishraghavendra @zhaodong-bsn
> [SWL-6518] ccf_feature -> swl_feature

- openflow_input/bsn_port_desc_properties
> Fix FEC caps spelling and add FEC_DISABLE caps.

- openflow_input/bsn_tlv
> Add src-mac to enum for packet field TLV

- openflow_input/bsn_tlv
Reviewer: @poolakiran @wilmo119
> SWL-6676: Added multicast tlvs

- openflow_input/bsn_tlv
Reverts floodlight/loxigen#702
> Revert "SWL-6676: Added multicast tlvs"
