- c_gen/c_code_gen.py
> loci: make of_mac_addr_all_zeroes name match the definition

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPort.java
Ports numbers greater than 32768 where being reported as negative.
> fix to support ports > 32768

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/EthType.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6FlowLabel.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IpDscp.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IpProtocol.java
Some value types' toString() functions output a hex value without the leading '0x'.
> Add '0x' prefix to the hex value in toString().

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFGroup.java
Well, that introduced another subtle bug. Using "new OFGroup(ZERO_VAL)" instead of "OFGroup.of(ZERO_VAL)" is the correct way to instantiate the ZERO object. It's null otherwise, which makes sense.
> Another fix for OFGroup.java

- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/OFPortDescTest.java
- java_gen/templates/_imports.java
- java_gen/templates/custom/OFPortDesc.java
- java_gen/templates/custom/interface/OFPortDesc.java
Reviewer: @rlane @Sovietaced 
CC: @sriniram 
This PR adds a convenience method to access the port generation id in the port desc.
> OFPortDesc: add convenience method to access BsnPortGenerationId

- openflow_input/bsn_tlv
Commit summary: ipv6 tlv is required to carry the switch management link local ip to be used by the sflow agent as agent ip.
> openflow_input: add ipv6 TLV

- openflow_input/bsn_vlan_counter
Reviewer: @harshsin
This message clears the stats reported by the extension for the given VLAN.
> openflow_input: add message of_bsn_vlan_counter_clear

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/IPAddressTest.java
Reviewer: @andi-bigswitch @Sovietaced
> Added IPAddress#toInetAddress() convenience method

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFMetadata.java
Change toString() of OFMetadata to not include the string 'Metadata:' before the value. No other type does this to my knowledge. We should probably remove it to be consistent with e.g. MacAddress, which is a hex string 'XX:XX:XX:XX:XX:XX', not 'MAC Address: XX:XX:XX:XX:XX:XX'.
> Change toString() of OFMetadata

- wireshark_gen/templates/openflow.lua
Reviewer: trivial
Newer versions of Wireshark crash (!) because of the name conflict.
> wireshark: rename to avoid conflict with upstream dissector

- openflow_input/bsn_port_counter
> Add link_up and link_down counters to ofp_bsn_port_counter.

- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/match/OFMatchPrerequisitesTest.java
- java_gen/templates/custom/OFMatchV3.java
Reviewer: @Sovietaced @wolverineav 
Previously, `isExact()`, `isPartiallyMasked()` and `isFullyWildcarded()`
did not check whether the required prerequisites for a field
had been set. get() and getMasked() did, leading to inconsistent
results / NPEs.
This makes all of the methods honor the prerequisite checks.
It also adds a unit test checking the behavior.
> Match: consistently hide Fields w/ broken prereqs LOXI-75

- openflow_input/bsn_pktin_flag
> Packet-in reason for reserved multicast packets.

- java_gen/java_model.py
- java_gen/templates/_field_accessors.java
- java_gen/templates/of_interface.java
Reviewer: @rlane
CC: @kenchiang 
This pull request replaces #439, which I am taking over from @rlane.
#438 ran into a problem when we tried to use a field as a discriminator when it was a normal data member in the superclass. The java compiler complained that we hadn't provided an 
implementation of the setter in the concrete class.
This PR improves on #439 in that the previous commit would add virtual Exception-raising setters
globally. This commit adds a method that specifically checks whether a setter is necessary.
A setter must be generated if the field is writeable in this class or any super class. Fields can turn non-writeable in a subclass if a superclass data member is used as a discriminator.
> java: generate setters for unwriteable fields LOXI-76

- openflow_input/standard-1.3
- openflow_input/standard-1.4
Reviewer: @rlane @Sovietaced 
Async request messages do not have any body. They only include the OF header w/async request type.
> Async request patch for OF1.3 and OF1.4

- openflow_input/standard-1.4
Reviewer: @rlane @Sovietaced 
Fixed OF1.4 table features properties byte alignment. Now byte aligned to 8 bytes. (Similar to https://github.com/floodlight/loxigen/pull/403)
> OF1.4 table features bug fix

- java_gen/templates/custom/OFPortDesc.java
- java_gen/templates/custom/interface/OFPortDesc.java
Reviewer: @rlane @andi-bigswitch 
Java 8 doesn't like doc syntax @link {...}, correct to {@link ...}. Java 7 appeared to accept syntax.
> Fix doc syntax, Java 8 does not like it

- java_gen/pre-written/pom.xml
Reviewer: @Sovietaced 
CC: @shudongz 
This PR upgrades the Guava dependency of openflowj to 19.0. The version was already upgraded in floodlight, which was causing problems.
> Upgrade Guava Version to 19.0

- c_gen/c_match.py
Reviewer: @wilmo119
of_memmask was passed the size of a pointer, not the match field.
> loci: fix mask size when parsing OXMs into of_match_t (SWL-2669)

- openflow_input/bsn_l2_cache_hit
> Support bsn_l2_cache_hit tlv in 1.4.

- openflow_input/bsn_tlv
Reviewer: @rlane @poolakiran @wilmo119 
Add TLVs for configuring port channel hash type, and the enhanced hash field table.
> Add tlv for port channel hashing

- openflow_input/bsn_tlv
Reviewer: @rlane @poolakiran 
This is a revision of TLVs for hashing GTP packets. For GTP, the hashing is always based on TEID, but user must define what is a GTP packet, based on first header byte and src/dst port. OF_BSN_HASH_PACKET_GTP is no longer needed.
Also remove OFP_BSN_HASH_FIELD_DISABLE. The absence of TLV indicates disable.
> Add TLVs for GTP match in the context of port-channel hashing

- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/OFBundleAddTest.java
- java_gen/templates/custom/OFBundleAddMsg.Builder_setData.java
- java_gen/templates/custom/OFBundleAddMsgVer14.Builder_setData.java
This pull request addresses #454, by ensuring that Builders for BundleAdd set the BundleAdd XID to the XID of the nested message, as required by the OF Spec, 1.4, section 7.3.9.6 Adding messages to a bundle:
> Message added in a bundle should have a unique xid to help matching
> errors to messages, and the xid of the bundle add message must be the
> same.
Rich, do we foresee any switch-side work that would be necessary as a result of this?
> Make Bundle-Add inherit the XID of the nested message  #loxigen/454

- openflow_input/bsn_queue_name
- openflow_input/standard-1.4
This will allow use to return names associated with queues.
It also looks like of_queue_desc_stats_request was missing two fields.
> Add of_queue_desc_prop_bsn and of_queue_desc_prop_bsn_queue_name

- .build/push-artifacts.sh
This is intended so we can easily inspect the artifact differences of
pull requests.
Jenkins integration pending.
> push-artifacts: add support to specify new target branch to be created

- docker.sh
- docker/Dockerfile
- docker/run-as-loxi
This creates a dockerized build environment for loxigen. The environment is built automatically, daily and pushed to DockerHub as `floodlight/loxi-builder-ubuntu14`. 
Also adds a convenience start script that puts the user into the docker image, ready to start build (`./docker.sh`).
> Dockerized build environment for loxigen

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/MatchField.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/Prerequisite.java
Reviewer: @rlane @andi-bigswitch 
It's useful to see what specific prerequisites are required for a particular MatchField. Having this visibility can allow one to compose flow-mods algorithmically and return more informative error messages for invalid flows without having to redefine the prerequisites at a higher level (i.e. within Floodlight modules) and in duplicate (the information is already set and is contained in OpenFlowJ-Loxi's MatchField.java).
> Expose MatchField prereqs

- openflow_input/standard-1.5
CC: @abakagamze 
The 'reserved' value in the stats object was currently exposed as a writeable field. This seemed kind-of ugly. I have made it a static field for now... @rlane - thoughts? - Should we make it a padding instead?
> standard-1.5:  fixed reserved value

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/stat/Stat.java
- java_gen/templates/custom/OFStatV6.Builder.java
- java_gen/templates/of_factory_class.java
- java_gen/templates/of_factory_interface.java
Reviewer: @Sovietaced 
CC: @abakagamze 
Stat mimics the design of the generic Match object. This commit
completes the set of convenience methods that abstract the details
and enable the user to set an abstract statfield.
> Java: V1.5 Stat: add convenience methods akin to Match

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/MacAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/util/HexString.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/util/HexStringTest.java
Reviewer: @ronaldchl @Sovietaced 
While debugging a performance problem related to `MacAddress.toString`, I noticed that the `HexString` conversion code we had was really old and inefficient. This code was even using anti-patterns like concatenating Strings without a StringBuilder (!).
These routines are used in a quite a lot of serialization cases, e.g., for DatapathIds.
This commit replaces the code with optimized implementations. These are necessarily relatively ugly and procedural.
JMH benchmarks show the new versions to be between 3.5 and 9.1x faster.
JMH Benchmark results:
Old versions:
```
Benchmark                                    Mode  Cnt        Score       Error  Units
HexStringBenchmark.testBytes6ToHexString    thrpt  200  5482128.668 ± 10011.236  ops/s …
```
> HexString: optimize performance; MacAddress: optimize putTo BVS-5367 LOXI-77

- java_gen/templates/custom/OFMatchV1Ver10.Builder.java
- java_gen/templates/custom/OFMatchV1Ver10.java
Reviewer: @rlane @andi-bigswitch 
Allow using the transport source and destination port match fields for ICMP type and code, respectively. This was mostly done, but was incomplete in getMatchFields(), resulting in the thrown exception.
> OF1.0 patch for ICMP type and code matches

- java_gen/templates/of_class.java
Reviewer: @rlane @andi-bigswitch 
For any class with an XID field (detected by a class field named 'xid'), include an equalsIgnoreXid() function to ignore the XID in the equality check. The assumption, of course, is that the XID field is named 'xid' and is a primitive type ('long' at present). This will allow for the content-comparison of two OFMessages without regard to when they were created (or what the XID was set to).
This will address the long-lived problem in Floodlight of not being able to use the OFMessageDamper to prevent rapid, duplicate messages from being sent to the switch. A workaround has been used the last couple years that rebuilds the 'other' object in the comparison with the XID of 'this', which is quite inefficient.
> Patch to optionally ignore the XID field in OFMessage and other types

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/MacAddress.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/MacAddressTest.java
Reviewer: @andi-bigswitch @ronaldchl 
This is to add a method to generate MacAddr corresponding to IPv6 Multicast address. A JUNIT test has been added too.
> BVS-6442: Adding MacAddr generation for IPv6 Mcast addresses.

- java_gen/templates/custom/interface/OFMessage.java
- java_gen/templates/of_class.java
- java_gen/templates/of_interface.java
Reviewer: @andi-bigswitch 
Otherwise, we have to cast to the specific implementing class to access the function. The assumption is that all implementers of OFMessage will have an equalsIgnoreXid() function generated for them, which they should and do.
Also, removed extra space from of_interface.java.
And lastly, introduce hashCodeIgnoreXid() for OFMessage and its implementing classes. This will allow us to hash an OFMessage disregarding the XID such that two or more OFMessages that are equal except for the XID field will produce the same hash.
> Add equalsIgnoreXid() + hashCodeIgnoreXid() to OFMessage

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/match/Match.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/protocol/stat/Stat.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/HashValue.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPAddress.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv4Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/IPv6Address.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFGroup.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPort.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPortBitMap.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/OFPortBitMap512.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/util/HexString.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/util/MultiplePktInReasonUtil.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/util/PrimitiveSinkUtils.java
Reviewer: @andi-bigswitch @rlane 
Clean up Javadoc. The Javadoc part of the build (make package-java) fails with Oracle JDK 1.8 due to warnings, which should probably be interpreted by the maven Javadoc plugin as warnings (and not errors). Nevertheless, the warnings have been fixed now by adding missing Javadoc annotations and correcting incomplete annotations.
Also, fix copy-and-paste errors:
(1) OFPortBitmask and OFPortBitmask512 set()/unset() functions had the same Javadoc comments
(2) PrimitiveSinkUtils putListTo() used 'set' variable name for a List, probably pasted from putSortedListTo() above it.
> Correct Javadoc to fix build failure when running 'make package-java'

- c_gen/templates/locitest/test_utils.c
- c_gen/templates/of_object.c
Reviewer: @wilmo119 
Previously only the wbuf and object lengths were reset. This resets the length
fields on the wire.
> loci: set wire length when truncating

- openflow_input/bsn_tlv
cc @meiyangbigswitch 
This tlv will be used in vxlan_access_vp table to indicate creation of a vxlan access virtual port for egress purpose only(for RioT decap case) and this will make the switch avoid installing a Vlan_xlate entry for the access virtual port.
> Add egress_only tlv

- openflow_input/bsn_tlv
Reviewer: @shudongz @andi-bigswitch 
These TLVs are intended to report what tunnels and enhanced hashing a switch is capable of.
In the case of the enhanced hash, it's possible that the switch will hash on a subset of all possible capabilities.  That is, certain switches can only hash on L2, L3, and MPLS packet fields, while other switches can hash on every field.
> Add tunnel and enhanced hash capabilities.

- java_gen/pre-written/pom.xml
Reviewer: @Sovietaced 
Bumping OpenFlowJ version for the new dev cycle...
> java/pom.xml: bump version to 3.2.0-SNAPSHOT for new dev cycle

- openflow_input/bsn_tlv
Reviewer: @andi-bigswitch @wilmo119 
It's a boolean for placing a switch interface in loopback mode, pretty straightforward.
> Add new tlv for loopback_mode

- openflow_input/bsn_tlv
-Add new TLV types for router_ip_table flag no_arp_response
-Add new TLV type for prefix table (IPv6) flag no_ns_response
> SWL-3685: Add new TLV types for router_ip table and prefix table flag

- openflow_input/bsn_tlv
Reviewer: @wilmo119 @kenchiang @shudongz 
CC: @jnealtowns 
* Added two new TLVs for port_config's forward-error-correction and optics-always-enabled
> [SWL-3678] Add two new TLVs for port_config gentable

- .build/push-artifacts.sh
Reviewer: trivial
CC: @ronaldchl 
This makes the MAKE command for push-artifacts configurable so that we can use the dockerized make (`./docker.sh make`) for this command.
> push-artifacts: make MAKE configurable

- openflow_input/bsn_tlv
Reviewer: @wilmo119 
CC: @shudongz @jnealtowns @andi-bigswitch 
* Add a new TLV **_force_link_up_** port property for future use as Shudong has suggested
* Passed unit test on DUT z9100-1
> [SWL-3678] Add a new TLV force_link_up for port_config gentable

- openflow_input/bsn_tlv
Reviewer: @wilmo119 @kenchiang 
I'm including a uint8_t for record_packets even though it's just a boolean... just in case we support more than on/off in the future.
> Add TLVs: REST server, URI scheme, and record packets

- .build/push-artifacts.sh
Reviewer: @ronaldchl 
.abat-automerge is currently still pushing artifacts, just as master is. This failed master build #2 here:
https://jenkins.bigswitch.com/view/Loxigen/job/floodlight%20Organization/job/loxigen/job/master/2/
I will remove the push artifacts from abat-automerge, but master builds should obviously not fail if you build the same commit twice in a row.
> don't fail pushartifacts if the artifact repo already has the commit

- openflow_input/bsn_tlv
Reviewer: @kenchiang 
CC: @chichong-bsn @skini-bsn
To distinguish the entries pushed from user configuration
vs entries pushed auto learning.
> SWL-4381 user_configured TLV.

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/TransportPort.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/TransportPortTest.java
Reviewer: trivial
CC: @Sovietaced @sdmodi 
Cherry-pick of #637 to the (newly) created bcf-4.7.x branch.
TransportPort is a short (2-byte) field; is is read and written as 2
bytes. However, for normalization purposes, we were looking for a 4-byte
0xFFFF_FFFF value to signify a fully set MASK (i.e., no bits marked
out).
This would mean that if the controller would send an OXe containing
tcp_dst_port_masked:1234/0xFFFF, the switch would store and report
back tcp_dst:1234 (unmasked), which would lead to VFT consistency
errors.
> [BCF-4.7.x] LOXI-81 LOXI-82: TransportPort - treat 0xFFFF as "NO_MASK"

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/PrimitiveSinkable.java
Reviewer: @rizard @Sovietaced 
A propos of BT-7898, I realized that the interface contract and caveats around `putTo` weren't documented in `PrimitiveSinkable`. Adding some documentation here.
> BT-7898: add javadoc on interface contract for PrimitiveSinkable

- openflow_input/bsn_tlv
Reviewer: @wilmo119 
CC: @shudongz 
Shudong, I want to make sure that the controller is checking tunnel_capability as a bitmask so it can handle the driver returning something like (OFP_BSN_TUNNEL_L2GRE | OFP_BSN_TUNNEL_VXLAN).
> Add OFP_BSN_TUNNEL_VXLAN.

- openflow_input/bsn_tlv
Reviewer: @poolakiran @shudongz 
This allows additional info to be reported to controller for redundant management interfaces.
> Add active, link_state, and fail_count TLVs

- java_gen/java_type.py
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U128.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U16.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U32.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U64.java
- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U8.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/protocol/match/PrimitiveNormalizationTest.java
- java_gen/templates/of_class.java
CC: @chichong-bsn @sdmodi 
We represent uint8,16,32 values by the next larger primitive numeric type in
Java, i.e., `uint8_t` is represented by `short`, not `byte`. This is done
because the Java types are internally signed and we want unsigned values
for output and input. (*)
However, this creates a problem if somebody inputs a value that is
partially represented by the underlying value, e.g., if they put in a
short "-1" to mean 0xFF. This is a fairly common practice, esp. in C.
Until now this could mean you could have two different OF objects containing a `uint8` — one
that has short '255' = `0xFF` and one that has short '-1' =`0xFFFF` in it. But because
the value uint_8 serializes to 8 bits on the wire, they would come out
to the same on the wire (and for the switch). Two OF objects …
> LOXI-83: normalize uint{8,16,32}_t values in ctors

- java_gen/pre-written/src/main/java/org/projectfloodlight/openflow/types/U16.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/U16Test.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/U32Test.java
- java_gen/pre-written/src/test/java/org/projectfloodlight/openflow/types/U8Test.java
Normalization, take to. Fixup for #649 
erroneous cast to short would make values greater than 32767 appears as signed/negative in U16. Exactly not what we want.
Also adds a unit test.
> LOXI-83: fix bug normalization of U16

- java_gen/pre-written/pom.xml
Bumping netty version to latest release version 4.1.42.Final
https://netty.io/news/2019/09/25/4-1-42-Final.html
> bump netty version

- loxigen.py
- openflow_input/standard-1.5
Reviewer: @andi-bigswitch 
Also throw errors when parsing instead of replacing undecodable characters
> Sanitize standard-1.5, removing nonascii values

- openflow_input/bsn_tlv
This specifies the data on which to match at a defined UDF ID.
> BT-8839 add UDF data TLV

- c_gen/c_test_gen.py
- lang_c.py
Reviewer: @archerhungbsn 
CC: @3mp4y5 
When more TLVs are added, locitest fails with memory issues ("test of_flow_stats_reply_OF_VERSION_1_3:memory clobbered before allocated block"), because the test messages are greater than 64kB in length.
Also, since the autogenerated files are long, gcc reports “variable tracking size limit exceeded with -fvar-tracking-assignments”.  This results in gcc backtraces with incorrect line numbers and makes debugging annoying.
This pull request has two commits: the first to break up the large autogenerated functions and files leading to the "variable tracking size limit exceeded" warnings, and the second to limit of_octets fields to 64B when populating them in the test code and to append only one of each possible subclass instead of two.
Regarding the …
> ctestgen fixes to avoid creating test messages > 64kB

- Makefile
- py_gen/codegen.py
- py_gen/templates/connection.py
Reviewer: @3mp4y5 
Rename "python" Makefile targets to "python2"
Explicitly invoke "python2" instead of relying on "python" symlink
> Generate python2 and python3 versions of connection.py

- c_gen/c_code_gen.py
Reviewer: @archerhungbsn 
I think these macros are left over from a long time ago.
> Remove dead code from loci_base.h

- loxi_utils/loxi_utils.py
- py_gen/templates/_pretty_print.py
- test_data/of10/flow_add.data
Reviewer: @3mp4y5 @archerhungbsn @harishraghavendra 
In python pretty_print methods, print both enum names and values for non-bitmask enums, and ORed flag names for bitmask enums
Previous behavior:
```
>>> import loxi.of14 as ofp
>>> import loxi.pp as pp
>>> tlv = ofp.bsn_tlv.packet_field(1)
>>> pp.pp(tlv)
'packet_field { value = 0x1 }'
```
New behavior:
```
>>> import loxi.of14 as ofp
>>> import loxi.pp as pp
>>> tlv = ofp.bsn_tlv.packet_field(1)
>>> pp.pp(tlv)
'packet_field { value = OFP_BSN_PACKET_FIELD_OUTER_VLAN_TAG_1(1) }'
```
> More user-friendly python pretty-printer output
